sudo: required

services:
  - docker

before_install:
  - docker build -t kba0708/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kba0708/react-test npm test -- --coverage

after_success:
  - docker build -t kba7/multi-client ./client
  - docker build -t kba7/multi-nginx ./nginx
  - docker build -t kba7/multi-server ./server
  - docker build -t kba7/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kba7/multi-client
  - docker push kba7/multi-nginx
  - docker push kba7/multi-server
  - docker push kba7/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-app"
  env: "MultiApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-728409497429"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

